export interface MCQQuestion {
  id: string;
  question: string;
  questionKm?: string;
  options: string[];
  optionsKm?: string[];
  correctIndex: number;
  explanation: string;
}

export interface QuizData {
  pagodaId: string;
  pagodaName: string;
  pagodaNameKm: string;
  location: string;
  image: any;
  color: string;
  accentColor: string;
  questions: MCQQuestion[];
}

export type PagodaQuizData = QuizData;

export const PAGODA_QUIZZES: QuizData[] = [
  {
    pagodaId: 'pagoda_1',
    pagodaName: 'Chùa Âng',
    pagodaNameKm: 'វត្តអង្គ',
    location: 'Phường 8, TP. Trà Vinh',
    image: require('@/assets/images/chuaang.jpg'),
    color: '#FF6B2C',
    accentColor: '#FFF3EE',
    questions: [
      {
        id: 'p1_q1',
        question: 'Chùa Âng tọa lạc tại tỉnh nào của Việt Nam?',
        options: ['Sóc Trăng', 'Trà Vinh', 'Cần Thơ', 'Vĩnh Long'],
        correctIndex: 1,
        explanation: 'Chùa Âng (Angkor Rajaborey) nằm tại Phường 8, TP. Trà Vinh, là ngôi chùa Khmer cổ kính và nổi tiếng nhất Trà Vinh.',
      },
      {
        id: 'p1_q2',
        question: 'Khuôn viên Chùa Âng nổi tiếng với hàng cây cổ thụ nào?',
        options: ['Cây dừa', 'Cây dầu', 'Cây xoài', 'Cây bồ đề'],
        correctIndex: 1,
        explanation: 'Chùa Âng nổi tiếng với hàng cây dầu cổ thụ hàng trăm năm tuổi, tạo nên không gian xanh mát và linh thiêng đặc trưng.',
      },
      {
        id: 'p1_q3',
        question: 'Chùa Âng được xây dựng vào khoảng thế kỷ nào?',
        options: ['Thế kỷ 5', 'Thế kỷ 7', 'Thế kỷ 10', 'Thế kỷ 15'],
        correctIndex: 2,
        explanation: 'Chùa Âng có lịch sử hơn 1.000 năm, được xây dựng vào khoảng thế kỷ thứ 10, là một trong những ngôi chùa cổ nhất vùng đồng bằng sông Cửu Long.',
      },
      {
        id: 'p1_q4',
        question: 'Kiến trúc Chùa Âng chịu ảnh hưởng phong cách của nền văn hóa nào?',
        options: ['Trung Hoa', 'Ấn Độ cổ đại', 'Java (Indonesia)', 'Angkor (Campuchia)'],
        correctIndex: 3,
        explanation: 'Chùa Âng mang kiến trúc đặc trưng phong cách Angkor với những đường nét tinh xảo, tháp nhọn và hoa văn trang trí đặc trưng văn hóa Khmer.',
      },
      {
        id: 'p1_q5',
        question: 'Người Khmer tại Chùa Âng theo tông phái Phật giáo nào?',
        options: ['Đại thừa (Mahayana)', 'Kim cương thừa', 'Nguyên thủy (Theravada)', 'Thiền tông'],
        correctIndex: 2,
        explanation: 'Phật giáo Nguyên thủy (Theravada) là tông phái chủ đạo của người Khmer Nam Bộ, khác với người Kinh chủ yếu theo Đại thừa.',
      },
    ],
  },
  {
    pagodaId: 'pagoda_2',
    pagodaName: 'Chùa Hang',
    pagodaNameKm: 'វត្តហ៊ាំង',
    location: 'TP. Trà Vinh, tỉnh Trà Vinh',
    image: require('@/assets/images/chuahang.jpg'),
    color: '#FF6B2C',
    accentColor: '#FFF3EE',
    questions: [
      {
        id: 'p2_q1',
        question: 'Chùa Hàng còn có tên tiếng Khmer là gì?',
        options: ['Kompissako', 'Veluvana', 'Âng Chum', 'Puthisomaran'],
        correctIndex: 0,
        explanation: 'Chùa Hàng có tên tiếng Khmer là Kompissako, là ngôi chùa nổi tiếng ở Trà Vinh với kiến trúc độc đáo.',
      },
      {
        id: 'p2_q2',
        question: 'Tên "Chùa Hàng" bắt nguồn từ đặc điểm kiến trúc nào của ngôi chùa?',
        options: ['Có hàng cây xanh trước cổng', 'Có hai hang đá ở hai bên cổng chính', 'Nằm bên hàng xóm chùa Âng', 'Có hàng tháp chuông nhỏ'],
        correctIndex: 1,
        explanation: 'Chùa Hàng nổi tiếng với hai công trình hình hang đá (grotte) xây hai bên cổng chính, là điểm kiến trúc độc đáo hiếm có khiến du khách dễ nhận ra.',
      },
      {
        id: 'p2_q3',
        question: 'Chùa Hàng thuộc địa phận tỉnh/thành phố nào?',
        options: ['TP. Sóc Trăng', 'TP. Cần Thơ', 'TP. Trà Vinh', 'TP. Vĩnh Long'],
        correctIndex: 2,
        explanation: 'Chùa Hàng (Kompissako) tọa lạc tại TP. Trà Vinh, tỉnh Trà Vinh, cùng địa bàn với Chùa Âng nổi tiếng.',
      },
      {
        id: 'p2_q4',
        question: 'Ngôi chùa Hàng thường tổ chức lễ hội lớn nhất vào dịp nào?',
        options: ['Chol Chnam Thmay (Tết Khmer)', 'Tết Nguyên Đán', 'Lễ Giáng Sinh', 'Tết Trung Thu'],
        correctIndex: 0,
        explanation: 'Chol Chnam Thmay (Tết Khmer) là lễ hội lớn nhất trong năm của người Khmer, thường diễn ra vào tháng 4 Dương lịch, được tổ chức trang trọng tại các chùa Khmer như Chùa Hàng.',
      },
      {
        id: 'p2_q5',
        question: 'Màu sắc đặc trưng nhất thường thấy trên kiến trúc các ngôi chùa Khmer như Chùa Hàng là?',
        options: ['Đỏ và đen', 'Trắng và xanh lam', 'Vàng và cam', 'Nâu đất và kem'],
        correctIndex: 2,
        explanation: 'Vàng và cam là hai màu đặc trưng của kiến trúc chùa Khmer, tượng trưng cho ánh sáng của Phật pháp và sự thịnh vượng trong văn hóa Khmer.',
      },
    ],
  },
  {
    pagodaId: 'pagoda_3',
    pagodaName: 'Chùa Kampong',
    pagodaNameKm: 'វត្តកំពង់',
    location: 'Tỉnh Trà Vinh',
    image: require('@/assets/images/kampong.jpg'),
    color: '#FF6B2C',
    accentColor: '#FFF3EE',
    questions: [
      {
        id: 'p3_q1',
        question: 'Trong tiếng Khmer, "Kampong" có nghĩa là gì?',
        options: ['Ngọn núi', 'Bến sông / Cảng nhỏ', 'Khu rừng', 'Cánh đồng lúa'],
        correctIndex: 1,
        explanation: '"Kampong" trong tiếng Khmer có nghĩa là bến/cảng nhỏ bên sông, cho thấy ngôi chùa này tọa lạc gần một bến sông, gắn liền với đời sống sông nước của người Khmer Nam Bộ.',
      },
      {
        id: 'p3_q2',
        question: 'Chùa Kampong thuộc tỉnh nào của Việt Nam?',
        options: ['Bạc Liêu', 'Kiên Giang', 'Trà Vinh', 'An Giang'],
        correctIndex: 2,
        explanation: 'Chùa Kampong tọa lạc tại tỉnh Trà Vinh, một trong những địa phương có đông người Khmer sinh sống và nhiều chùa Khmer cổ kính nhất.',
      },
      {
        id: 'p3_q3',
        question: 'Ngôi chùa Kampong thờ ai là chủ yếu?',
        options: ['Thần Hindu', 'Đức Phật Thích Ca Mâu Ni', 'Thần Naga (rắn thần)', 'Tổ tiên người Khmer'],
        correctIndex: 1,
        explanation: 'Toàn bộ các chùa Khmer theo Phật giáo Nguyên thủy đều thờ Đức Phật Thích Ca Mâu Ni là trung tâm, với những tượng Phật được chạm khắc công phu.',
      },
      {
        id: 'p3_q4',
        question: 'Biểu tượng rắn Naga trong kiến trúc chùa Kampong tượng trưng cho điều gì?',
        options: ['Điềm xấu và thử thách', 'Thần bảo hộ và phồn thịnh', 'Chiến tranh và sức mạnh', 'Cái chết và tái sinh'],
        correctIndex: 1,
        explanation: 'Rắn Naga (rồng) là biểu tượng quan trọng trong kiến trúc Khmer, tượng trưng cho thần bảo hộ, sự phồn thịnh và nguồn nước dồi dào – rất quan trọng với người Khmer sống gần sông.',
      },
      {
        id: 'p3_q5',
        question: 'Sư sãi trong chùa Kampong thực hiện nghi thức quan trọng nào mỗi sáng?',
        options: ['Đi khất thực (bình bát)', 'Lên núi cầu nguyện', 'Tắm sông lúc bình minh', 'Đọc kinh Vệ Đà'],
        correctIndex: 0,
        explanation: 'Nghi thức đi khất thực (khất thực bình bát) mỗi sáng sớm là truyền thống thiêng liêng của các sư sãi Phật giáo Nguyên thủy tại các chùa Khmer, thể hiện sự gắn kết giữa tu sĩ và cộng đồng.',
      },
    ],
  },
  {
    pagodaId: 'pagoda_4',
    pagodaName: 'Chùa Sà Lôn',
    pagodaNameKm: 'វត្តសាឡុន',
    location: 'Huyện Mỹ Xuyên, Sóc Trăng',
    image: require('@/assets/images/salengcu.jpg'),
    color: '#FF6B2C',
    accentColor: '#FFF3EE',
    questions: [
      {
        id: 'p4_q1',
        question: 'Chùa Sà Lôn (Chùa Chén Kiểu) tọa lạc tại tỉnh nào?',
        options: ['Trà Vinh', 'Cần Thơ', 'Sóc Trăng', 'Bạc Liêu'],
        correctIndex: 2,
        explanation: 'Chùa Sà Lôn, còn gọi là Chùa Chén Kiểu, tọa lạc tại huyện Mỹ Xuyên, tỉnh Sóc Trăng – nơi có cộng đồng người Khmer đông đúc nhất vùng đồng bằng sông Cửu Long.',
      },
      {
        id: 'p4_q2',
        question: 'Chùa Sà Lôn có biệt danh phổ biến bắt nguồn từ đặc điểm nào?',
        options: ['Xây bằng toàn đá cẩm thạch', 'Được trang trí bằng hàng nghìn mảnh chén sứ', 'Có hồ sen khổng lồ', 'Mái chùa hình lưỡi kiếm'],
        correctIndex: 1,
        explanation: 'Chùa Sà Lôn còn gọi là "Chùa Chén Kiểu" vì toàn bộ bề mặt kiến trúc được trang trí, ốp lát bằng hàng nghìn mảnh chén, đĩa sứ vỡ ghép lại tạo thành những hoa văn độc đáo, là kỹ thuật trang trí hiếm có.',
      },
      {
        id: 'p4_q3',
        question: 'Nguyên liệu trang trí đặc trưng của Chùa Sà Lôn là gì?',
        options: ['Đá granit chạm khắc', 'Gốm sứ và mảnh chén vỡ', 'Vàng lá dát mỏng', 'Gỗ quý khắc nổi'],
        correctIndex: 1,
        explanation: 'Chùa Sà Lôn nổi tiếng với kỹ thuật trang trí bằng các mảnh chén, bát, đĩa sứ được ghép lại khéo léo tạo thành những họa tiết hoa văn Khmer tinh xảo, là di sản nghệ thuật độc đáo.',
      },
      {
        id: 'p4_q4',
        question: 'Lễ hội Dolta của người Khmer (tổ chức tại các chùa như Chùa Sà Lôn) tương đương với lễ nào của người Kinh?',
        options: ['Tết Nguyên Đán', 'Lễ Vu Lan (Rằm tháng 7)', 'Tết Trung Thu', 'Lễ Giỗ Tổ Hùng Vương'],
        correctIndex: 1,
        explanation: 'Lễ Dolta (Sen Dolta) của người Khmer diễn ra vào tháng 8 – 9 Âm lịch, là dịp tưởng nhớ tổ tiên, tương tự như lễ Vu Lan của người Kinh. Đây là một trong ba lễ hội lớn nhất của người Khmer.',
      },
      {
        id: 'p4_q5',
        question: 'Tỉnh Sóc Trăng có bao nhiêu dân tộc chính cùng sinh sống hòa hợp?',
        options: ['2 dân tộc', '3 dân tộc', '5 dân tộc', '7 dân tộc'],
        correctIndex: 1,
        explanation: 'Sóc Trăng là tỉnh có 3 dân tộc chính cùng sinh sống hòa hợp: người Kinh, người Khmer và người Hoa. Cộng đồng đa dân tộc này tạo nên bản sắc văn hóa phong phú và đặc sắc của địa phương.',
      },
    ],
  },
  {
    pagodaId: 'pagoda_5',
    pagodaName: 'Chùa Veluvana',
    pagodaNameKm: 'វត្តវេឡុវ័ន',
    location: 'Tỉnh Sóc Trăng',
    image: require('@/assets/images/veluvana.jpg'),
    color: '#FF6B2C',
    accentColor: '#FFF3EE',
    questions: [
      {
        id: 'p5_q1',
        question: '"Veluvana" là từ trong ngôn ngữ nào của Phật giáo?',
        options: ['Sanskrit (Phạn ngữ)', 'Pali', 'Tiếng Khmer cổ', 'Tiếng Hán cổ'],
        correctIndex: 1,
        explanation: '"Veluvana" là từ tiếng Pali – ngôn ngữ kinh điển của Phật giáo Nguyên thủy. Pali là ngôn ngữ được dùng để ghi chép Tam Tạng kinh điển và vẫn được các sư sãi Khmer Theravada học tập đến ngày nay.',
      },
      {
        id: 'p5_q2',
        question: 'Trong tiếng Pali, "Veluvana" có nghĩa là gì?',
        options: ['Núi thiêng liêng', 'Vườn tre (Trúc Lâm)', 'Dòng sông thánh', 'Ánh sáng mặt trời'],
        correctIndex: 1,
        explanation: '"Veluvana" nghĩa là "Vườn tre" hay "Trúc Lâm" trong tiếng Pali. Đây là tên của khu vườn nổi tiếng trong lịch sử Phật giáo, nơi Đức Phật từng cư trú và thuyết pháp.',
      },
      {
        id: 'p5_q3',
        question: 'Veluvana trong kinh Phật là khu vườn được vua Bimbisara dâng tặng cho Đức Phật, nằm ở vùng đất nào?',
        options: ['Vương quốc Magadha (Ấn Độ cổ)', 'Vương quốc Campuchia cổ', 'Vương quốc Siam (Thái Lan)', 'Vương quốc Ayutthaya'],
        correctIndex: 0,
        explanation: 'Veluvana là khu vườn tre tại Rajagaha, thuộc Vương quốc Magadha (nay là bang Bihar, Ấn Độ). Vua Bimbisara đã dâng tặng khu vườn này cho Đức Phật, và đây trở thành nơi Phật trú ngụ và truyền pháp.',
      },
      {
        id: 'p5_q4',
        question: 'Chùa Veluvana ở Sóc Trăng theo tông phái Phật giáo nào?',
        options: ['Phật giáo Đại thừa', 'Phật giáo Nguyên thủy (Theravada)', 'Phật giáo Mật tông', 'Phật giáo Thiền tông'],
        correctIndex: 1,
        explanation: 'Cũng như tất cả các chùa Khmer khác tại Việt Nam, Chùa Veluvana theo Phật giáo Nguyên thủy (Theravada) – tông phái gần nhất với Phật giáo thời kỳ đầu, được lưu truyền qua các dân tộc Đông Nam Á như Khmer, Thái, Myanmar.',
      },
      {
        id: 'p5_q5',
        question: 'Trong các chùa Khmer Theravada như Veluvana, hình tượng Phật thường được thể hiện ở tư thế nào?',
        options: ['Phật đứng giơ tay', 'Phật ngồi xếp bằng (Thiền định)', 'Phật nằm (Niết bàn)', 'Cả ba đều phổ biến'],
        correctIndex: 3,
        explanation: 'Trong chùa Khmer Theravada, người ta thờ Phật với nhiều tư thế: Phật ngồi thiền định (tượng trưng giác ngộ), Phật đứng (từ bi), và Phật nằm (Niết bàn). Cả ba tư thế đều phổ biến và mang ý nghĩa giáo lý sâu sắc.',
      },
    ],
  },
  {
    pagodaId: 'culture_1',
    pagodaName: 'Văn hóa chùa chiền',
    pagodaNameKm: 'វប្បធម៌វត្តអារាម',
    location: 'Nam Bộ',
    image: require('@/assets/images/pagoda.jpg'),
    color: '#6366F1',
    accentColor: '#EEF2FF',
    questions: [
      {
        id: 'c1_q1',
        question: 'Chùa Khmer thường có kiến trúc mái như thế nào?',
        options: ['Mái bằng', 'Mái nhọn nhiều tầng', 'Mái vòm', 'Mái ngói âm dương'],
        correctIndex: 1,
        explanation: 'Mái chùa Khmer thường có kiến trúc nhọn, nhiều tầng chồng lên nhau, tượng trưng cho núi Meru trong thần thoại.',
      },
      {
        id: 'c1_q2',
        question: 'Chùa đối với cộng đồng người Khmer đóng vai trò gì?',
        options: ['Nơi ở của dân làng', 'Trung tâm văn hóa, giáo dục và tín ngưỡng', 'Chợ mua bán', 'Nơi hội họp chính trị'],
        correctIndex: 1,
        explanation: 'Ngôi chùa là trung tâm của mọi sinh hoạt cộng đồng, từ tôn giáo đến giáo dục và bảo tồn văn hóa của người Khmer.',
      },
      {
        id: 'c1_q3',
        question: 'Phật giáo của người Khmer Nam Bộ thuộc tông phái nào?',
        options: ['Phật giáo Đại thừa', 'Phật giáo Nam tông (Nguyên thủy)', 'Thiền tông', 'Mật tông'],
        correctIndex: 1,
        explanation: 'Phật giáo Nam tông (Theravada) là tôn giáo chủ đạo, ảnh hưởng sâu sắc đến nếp sống của người Khmer.',
      },
      {
        id: 'c1_q4',
        question: 'Ai là người có vị trí cao nhất, trụ trì một ngôi chùa Khmer?',
        options: ['Sư cả (Mekon)', 'Sư phó', 'Sa di', 'Cư sĩ'],
        correctIndex: 0,
        explanation: 'Sư cả là người đứng đầu ngôi chùa, có uy tín và vai trò lớn trong việc dẫn dắt đời sống tâm linh cộng đồng.',
      },
      {
        id: 'c1_q5',
        question: 'Các kinh sách cổ của người Khmer thường được lưu giữ trên chất liệu gì?',
        options: ['Giấy da', 'Lá buông (Lá thốt nốt)', 'Vải lụa', 'Gỗ quý'],
        correctIndex: 1,
        explanation: 'Kinh Lá Buông là di sản quý giá, được khắc chữ trên lá cây buông sấy khô, có độ bền hàng trăm năm.',
      },
    ],
  },
  {
    pagodaId: 'culture_2',
    pagodaName: 'Lễ hội truyền thống',
    pagodaNameKm: 'ពិធីបុណ្យប្រពៃណី',
    location: 'Nam Bộ',
    image: require('@/assets/images/lehoi.jpg'),
    color: '#EC4899',
    accentColor: '#FDF2F8',
    questions: [
      {
        id: 'c2_q1',
        question: 'Hoạt động đặc trưng nhất của lễ hội Oóc Om Bóc là gì?',
        options: ['Múa lân', 'Đua ghe Ngo', 'Kéo co', 'Đấu vật'],
        correctIndex: 1,
        explanation: 'Đua ghe Ngo là môn thể thao dân gian sôi động và quan trọng nhất trong lễ hội Oóc Om Bóc.',
      },
      {
        id: 'c2_q2',
        question: 'Tết cổ truyền của người Khmer được gọi là gì?',
        options: ['Sen Đôn-ta', 'Chol Chnam Thmay', 'Oóc Om Bóc', 'Kathina'],
        correctIndex: 1,
        explanation: 'Chol Chnam Thmay là lễ mừng năm mới của người Khmer, diễn ra vào khoảng giữa tháng 4 hàng năm.',
      },
      {
        id: 'c2_q3',
        question: 'Lễ hội nào nhằm tưởng nhớ và báo hiếu tổ tiên?',
        options: ['Sen Đôn-ta', 'Lễ Kathina', 'Lễ hội Đua bò', 'Lễ cúng Trăng'],
        correctIndex: 0,
        explanation: 'Sen Đôn-ta (Lễ cúng ông bà) là dịp để con cháu bày tỏ lòng biết ơn và cầu siêu cho tổ tiên.',
      },
      {
        id: 'c2_q4',
        question: 'Lễ hội Oóc Om Bóc còn được gọi là lễ cúng vị thần nào?',
        options: ['Thần Nước', 'Thần Mặt Trăng', 'Thần Đất', 'Thần Gió'],
        correctIndex: 1,
        explanation: 'Oóc Om Bóc là lễ cúng Trăng, cảm ơn thần Mặt Trăng đã ban cho mùa màng tốt tươi.',
      },
      {
        id: 'c2_q5',
        question: 'Lễ dâng y Kathina thường diễn ra sau kỳ hạn nào của các vị sư?',
        options: ['Kỳ thi kinh', 'Ba tháng an cư kiết hạ', 'Tết Nguyên đán', 'Lễ hội đua ghe'],
        correctIndex: 1,
        explanation: 'Lễ dâng y Kathina được tổ chức sau khi các vị sư hoàn tất 3 tháng an cư kiết hạ tại chùa.',
      },
    ],
  },
  {
    pagodaId: 'culture_3',
    pagodaName: 'Nghệ thuật và Âm nhạc',
    pagodaNameKm: 'សិល្បៈ និងតន្ត្រី',
    location: 'Nam Bộ',
    image: require('@/assets/images/festival.jpg'),
    color: '#F59E0B',
    accentColor: '#FFFBEB',
    questions: [
      {
        id: 'c3_q1',
        question: 'Điệu múa dân gian phổ biến nhất của người Khmer là gì?',
        options: ['Múa sạp', 'Múa Răm-vông', 'Múa quạt', 'Múa nón'],
        correctIndex: 1,
        explanation: 'Múa Răm-vông là điệu múa vòng tròn, đơn giản nhưng vô cùng duyên dáng và có tính cộng đồng cao.',
      },
      {
        id: 'c3_q2',
        question: 'Dàn nhạc truyền thống đặc sắc nhất của người Khmer có tên là gì?',
        options: ['Dàn nhạc Giao hưởng', 'Dàn nhạc Ngũ âm (Pin Peat)', 'Dàn nhạc Cống chiêng', 'Dàn nhạc Đờn ca tài tử'],
        correctIndex: 1,
        explanation: 'Dàn nhạc Ngũ âm gồm các nhạc cụ làm từ kim loại, mộc, dây, da và hơi, tạo nên âm hưởng đặc trưng.',
      },
      {
        id: 'c3_q3',
        question: 'Loại hình sân khấu kịch hát truyền thống của người Khmer là?',
        options: ['Cải lương', 'Dù-kê', 'Hát bội', 'Quan họ'],
        correctIndex: 1,
        explanation: 'Dù-kê là loại hình nghệ thuật sân khấu tổng hợp độc đáo, kết hợp giữa ca, múa, kịch và âm nhạc.',
      },
      {
        id: 'c3_q4',
        question: 'Nhạc cụ Rô-niết-ek trong dàn nhạc Ngũ âm là loại nhạc cụ gì?',
        options: ['Trống da', 'Đàn thuyền bằng gỗ (Xylophone)', 'Kèn', 'Trống đồng'],
        correctIndex: 1,
        explanation: 'Rô-niết-ek là chiếc đàn hình thuyền với các thanh gỗ hoặc tre, phát ra âm thanh thanh thoát.',
      },
      {
        id: 'c3_q5',
        question: 'Múa Robam thường diễn ra trong bối cảnh nào?',
        options: ['Múa cung đình truyền thống', 'Nhảy hiện đại', 'Hát karaoke', 'Lao động sản xuất'],
        correctIndex: 0,
        explanation: 'Robam là nghệ thuật múa cổ điển Khmer, thường diễn các tích truyện về các vị thần và anh hùng.',
      },
    ],
  },
  {
    pagodaId: 'culture_4',
    pagodaName: 'Ngôn ngữ và Chữ viết',
    pagodaNameKm: 'ភាសា និងអក្សរសាស្ត្រ',
    location: 'Nam Bộ',
    image: require('@/assets/images/hoctap.jpg'),
    color: '#10B981',
    accentColor: '#ECFDF5',
    questions: [
      {
        id: 'c4_q1',
        question: 'Chữ viết Khmer có nguồn gốc từ hệ chữ nào?',
        options: ['Chữ Hán', 'Chữ Latinh', 'Chữ Brahmi (Ấn Độ cổ)', 'Chữ Nôm'],
        correctIndex: 2,
        explanation: 'Hệ chữ Khmer được hình thành dựa trên nền tảng chữ Brahmi của Ấn Độ cổ đại.',
      },
      {
        id: 'c4_q2',
        question: 'Phụ âm trong tiếng Khmer có bao nhiêu ký tự chính?',
        options: ['24', '33', '29', '36'],
        correctIndex: 1,
        explanation: 'Hệ thống chữ viết Khmer có 33 phụ âm cơ bản, chia làm hai nhóm giọng (giọng O và giọng Ô).',
      },
      {
        id: 'c4_q3',
        question: 'Tiếng Khmer thuộc ngữ hệ nào sau đây?',
        options: ['Ngữ hệ Hán-Tạng', 'Ngữ hệ Nam Á (Môn-Khmer)', 'Ngữ hệ Nam Đảo', 'Ngữ hệ Ấn-Âu'],
        correctIndex: 1,
        explanation: 'Tiếng Khmer là ngôn ngữ lớn thứ hai trong ngữ hệ Nam Á, sau tiếng Việt.',
      },
      {
        id: 'c4_q4',
        question: 'Nơi nào thường xuyên tổ chức dạy chữ viết Khmer cho trẻ em?',
        options: ['Nhà văn hóa', 'Các ngôi chùa Khmer', 'Trường tiểu học công lập', 'Trung tâm giáo dục thường xuyên'],
        correctIndex: 1,
        explanation: 'Truyền thống dạy chữ Khmer trong chùa vào mỗi dịp hè là cách bảo tồn ngôn ngữ quan trọng của đồng bào.',
      },
      {
        id: 'c4_q5',
        question: 'Tiếng Khmer là ngôn ngữ chính của cộng đồng dân tộc nào tại ĐBSCL?',
        options: ['Người Hoa', 'Người Chăm', 'Người Khmer', 'Người Kinh'],
        correctIndex: 2,
        explanation: 'Tiếng Khmer là ngôn ngữ mẹ đẻ và là phương tiện giao tiếp chính của đồng bào dân tộc Khmer.',
      },
    ],
  },
  {
    pagodaId: 'culture_5',
    pagodaName: 'Trang phục truyền thống',
    pagodaNameKm: 'សម្លៀកបំពាក់ប្រពៃណី',
    location: 'Nam Bộ',
    image: require('@/assets/images/giadinh.jpg'),
    color: '#8B5CF6',
    accentColor: '#F5F3FF',
    questions: [
      {
        id: 'c5_q1',
        question: 'Trang phục quấn quanh thân dưới của người Khmer gọi là gì?',
        options: ['Quần đùi', 'Xà-rông (Sampot)', 'Váy đầm', 'Áo dài'],
        correctIndex: 1,
        explanation: 'Xà-rông là trang phục truyền thống phổ biến nhất, được quấn khéo léo quanh hông.',
      },
      {
        id: 'c5_q2',
        question: 'Màu sắc chủ đạo trong trang phục cưới của người Khmer là màu gì?',
        options: ['Màu đen', 'Màu vàng rực rỡ', 'Màu trắng', 'Màu xanh lá'],
        correctIndex: 1,
        explanation: 'Màu vàng tượng trưng cho sự may mắn, quý phái và là màu sắc hoàng gia, tôn giáo trọng tâm.',
      },
      {
        id: 'c5_q3',
        question: 'Khăn rằn đặc trưng của người Khmer có tên gọi là gì?',
        options: ['Khăn K-ra-ma', 'Khăn Piêu', 'Khăn đóng', 'Khăn len'],
        correctIndex: 0,
        explanation: 'Khăn K-ra-ma (Krama) was vật dụng không thể thiếu, dùng để quấn đầu, quàng cổ hoặc làm thắt lưng.',
      },
      {
        id: 'c5_q4',
        question: 'Phụ nữ Khmer thường mặc loại áo nào khi đi lễ chùa?',
        options: ['Áo phông', 'Áo Tầm-vông', 'Áo yếm', 'Áo khoác'],
        correctIndex: 1,
        explanation: 'Áo Tầm-vông kết hợp with Xà-rông tạo nên vẻ đẹp kín đáo và trang nghiêm khi đi lễ Phật.',
      },
      {
        id: 'c5_q5',
        question: 'Trang phục Sampot Chang Kben thường được mặc trong dịp nào?',
        options: ['Đi làm ruộng', 'Các nghi lễ trang trọng, lễ cưới', 'Đi ngủ', 'Đi đá bóng'],
        correctIndex: 1,
        explanation: 'Sampot Chang Kben là cách quấn xà-rông cầu kỳ qua háng, thường dành cho các nghi lễ quan trọng.',
      },
    ],
  },
];
