import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'vi' | 'km';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const translations: any = {
  vi: {
    // Common
    leaderboard: 'Bảng xếp hạng',
    weekly: 'Hàng tuần',
    all_time: 'Tất cả',
    settings: 'Cài đặt ứng dụng',
    language: 'Ngôn ngữ',
    vietnamese: 'Tiếng Việt',
    khmer: 'Tiếng Khmer',
    back: 'Quay lại',
    confirm: 'Xác nhận',
    close: 'Đóng',
    save: 'Lưu',
    cancel: 'Huỷ',
    next: 'Huy hiệu',
    continue: 'Tiếp tục chơi',
    exit: 'Thoát',
    login: 'Đăng nhập tài khoản',
    login_user: 'Đăng nhập',

    // Settings Screen
    notif_settings: 'Thông báo',
    study_reminder: 'Nhắc học bài mỗi ngày',
    reminder_time: 'Thời gian nhắc',
    app_info: 'Thông tin ứng dụng',
    intro: 'Giới thiệu',
    version: 'Phiên bản',
    assistant_settings: 'Cài đặt trợ lý AI',
    show_chat_button: 'Hiển thị trợ lý AI',
    // Support Screen
    support_feedback: 'Phản hồi người dùng',
    feedback_type: 'Loại phản hồi',
    suggestion: 'Góp ý',
    report_issue: 'Báo lỗi',
    subject: 'Tiêu đề',
    detail: 'Nội dung chi tiết',
    send_feedback: 'Gửi phản hồi',
    login_to_send: 'Đăng nhập để gửi phản hồi',
    // Profile Screen
    my_profile: 'Hồ sơ của tôi',
    edit_profile: 'Chỉnh sửa hồ sơ',
    favorites: 'Nội dung yêu thích',
    achievements: 'Thành tích của tôi',
    medal: 'Thành tích xếp hạng',
    logout: 'Đăng xuất',
    logout_full: 'Đăng xuất tài khoản',
    points: 'Điểm',
    rank: 'Top',
    guest: 'Khách',
    login_to_view: 'Đăng nhập để xem thông tin',
    login_to_use: 'Đăng nhập để sử dụng tính năng này',
    logout_confirm_msg: 'Bạn có chắc chắn muốn đăng xuất',
    login_required: 'Yêu cầu đăng nhập',
    login_to_fav_msg: 'Vui lòng đăng nhập để lưu và xem danh sách yêu thích của bạn',
    login_now: 'Đăng nhập ngay',
    no_favorites_yet: 'Chưa có yêu thích nào',
    explore_and_save_favs: 'Khám phá và lưu lại những điều bạn yêu thích nhé',
    badge: 'Huy hiệu',
    badge_bronze: 'Đồng',
    badge_silver: 'Bạc',
    badge_gold: 'Vàng',
    badge_platinum: 'Bạch Kim',
    badge_diamond: 'Kim cương',
    badge_legend: 'Huyền thoại',
    rank_progress: 'Tiến trình thử thách',
    badge_locked: 'Chưa đạt được',
    badge_unlocked: 'Đã đạt được',
    quizzes_completed: 'Quiz hoàn thành',
    badge_locked_message: 'Cần đạt {points} điểm \n Để nhận được huy hiệu {name}',
    congrats_earned: 'Chúc mừng bạn \n Đã sở hữu huy hiệu',

    // Quiz Screen
    quiz_title: 'Thử thách',
    question: 'Câu',
    start_quiz: 'Bắt đầu',
    daily_challenge: 'Thử thách hằng ngày',
    correct: 'Chính xác',
    wrong_answer: 'Sai rồi',
    quiz_desc: 'Vượt qua các câu hỏi để tích lũy thêm điểm',
    total_score: 'Tổng điểm',
    current_rank: 'Hạng hiện tại',
    categories: 'Chủ đề thử thách',
    questions: 'Bộ câu hỏi',
    performance: 'Thành tích',
    view_all: 'Xem tất cả...',
    completed: 'Hoàn thành',
    recent_performance: 'Dựa trên các bài thi gần đây',
    choose_topic: 'Hôm nay bạn muốn thử thách về chủ đề gì nào',
    pagoda_quiz: 'Ngôi chùa Khmer',
    culture_quiz: 'Văn hóa Khmer',
    food_quiz: 'Ẩm thực Khmer',
    vocab_quiz: 'Học tiếng Khmer',
    vocab_quiz_subtitle: 'Ghép tiếng Khmer - tiếng Việt',
    vocab_challenge_questions: 'câu hỏi thử thách từ vựng',
    correct_answer_points_msg: 'Cộng 5 điểm cho mỗi câu đúng',
    login_required_long_msg: 'Bạn cần đăng nhập để tham gia thử thách và tích luỵ điểm xếp hạng',
    exit_game_title: 'Thoát khỏi trò chơi',
    exit_game_msg: 'Tiến trình hiện tại của bạn sẽ\nkhông được lưu lại',
    replay: 'Chơi lại',
    choose_another_quiz: 'Chọn bộ câu hỏi khác',
    answered_correctly: 'Trả lời đúng',
    questions_count: 'câu',
    points_earned: 'Điểm vừa tích luỹ',
    saving_results: 'Đang lưu thành tích...',
    results_saved: 'Đã lưu thành tích',
    excellent: '🎉 Xuất sắc',
    well_done: '👏 Tốt lắm',
    keep_it_up: '💪 Cố lên',
    amazing: '🎉 Tuyệt vời',
    incorrect: 'Chưa chính xác',
    correct_answer_label: 'Đáp án đúng',
    continue_btn: 'Tiếp tục',
    saving_points: 'Đang lưu điểm...',
    loading_questions: 'Đang tải câu hỏi...',
    not_logged_in_title: 'Bạn chưa đăng nhập',
    login_to_save_points: 'Hãy đăng nhập để lưu lại thành tích\nvà tích luỹ điểm thưởng nhé!',
    guest_login_msg: 'Bạn cần đăng nhập để tham gia thử thách,\nlưu lại thành tích và tích luỹ điểm thưởng.',
    maybe_later: 'Để sau',
    go_back_now: 'Để sau, quay lại',
    preview_mode: 'Chế độ xem trước',
    question_label: 'Câu',
    stay_and_play: 'Tiếp tục chơi',
    points_badge_unlocked: '+ {points} điểm',
    badge_reached_level: 'Bạn đã đạt cấp độ {rank}',
    badge_unlocked_name: 'Bạn đã mở khóa huy hiệu {rank}',
    badge_bronze_msg: 'Chúc mừng bạn đã mở khóa huy hiệu Đồng....',
    badge_silver_msg: 'Chúc mừng bạn đã mở khóa huy hiệu Bạc...',
    badge_gold_msg: 'Chúc mừng bạn đã mở khóa huy hiệu Vàng...',
    badge_platinum_msg: 'Chúc mừng bạn đã mở khóa huy hiệu Bạch Kim...',
    badge_diamond_msg: 'Chúc mừng bạn đã mở khóa huy hiệu Kim Cương...',
    badge_legend_msg: 'Chúc mừng bạn đã trở thành Huyền Thoại KhmerGo...',
    rank_bronze: 'Đồng',
    rank_silver: 'Bạc',
    rank_gold: 'Vàng',
    rank_platinum: 'Bạch Kim',
    rank_diamond: 'Kim Cương',
    rank_legend: 'Huyền Thoại',

    // Matching Game
    matching_challenge: 'Ghép từ vựng',
    matching_challenge_title: 'Thử thách Ghép từ',
    matching_challenge_desc: 'Hãy ghép các cặp từ Khmer và nghĩa tiếng Việt tương ứng thật nhanh nhé',
    start_matching: 'Bắt đầu ghép từ',

    // Personal Info
    personal_info: 'Thông tin cá nhân',
    full_name: 'Họ và tên',
    email: 'Email',
    change_password: 'Đổi mật khẩu',
    current_password: 'Mật khẩu hiện tại',
    new_password: 'Mật khẩu mới',
    confirm_new_password: 'Xác nhận mật khẩu mới',
    save_changes: 'Lưu thay đổi',
    error: 'Lỗi',
    name_required: 'Họ và tên không được để trống',
    unsaved_changes: 'Thay đổi chưa lưu',
    exit_confirm_msg: 'Bạn có chắc chắn muốn thoát? Các thay đổi của bạn sẽ bị mất',
    stay: 'Ở lại',
    not_logged_in: 'Chưa đăng nhập',
    pass_fields_required: 'Vui lòng điền đầy đủ các trường để đổi mật khẩu',
    pass_mismatch: 'Mật khẩu mới không khớp',
    pass_too_short: 'Mật khẩu mới tối thiểu 6 ký tự',
    user_not_found: 'Không tìm thấy tài khoản',
    wrong_old_pass: 'Mật khẩu hiện tại không chính xác',
    update_success: 'Cập nhật thông tin thành công',
    update_failed: 'Cập nhật thất bại',

    // Support Screen Extra
    feedback_section: 'Gửi phản hồi cho chúng tôi',
    feedback_placeholder: 'Nhập nội dung phản hồi...',
    subject_placeholder: 'Nhập tiêu đề phản hồi...',
    subject_required: 'Vui lòng nhập tiêu đề và nội dung',
    content_required: 'Vui lòng nhập nội dung phản hồi',
    feedback_success: 'Đã gửi phản hồi thành công',
    feedback_failed: 'Gửi phản hồi thất bại',
    delete_feedback_success: 'Đã xóa nội dung phản hồi',
    delete_feedback_failed: 'Không thể xóa phản hồi',
    feedback_history: 'Lịch sử phản hồi',
    no_feedback_history: 'Chưa có lịch sử phản hồi',
    feedback_content_label: 'Nội dung',
    no_content: 'Không có nội dung',
    system_reply: 'Hệ thống phản hồi',
    no_feedback_yet: 'Bạn chưa có phản hồi nào',
    tap_to_see_guide: 'Bấm để xem hướng dẫn chi tiết',
    replied_status: 'Đã phản hồi',
    pending_status: 'Chờ phản hồi',
    admin_reply: 'Hệ thống phản hồi',

    // Home Screen
    promotions: 'Khám phá ngay',
    category: 'Danh mục',
    see_all: 'Xem tất cả...',
    get_coupon: 'Xem',
    learn_now: 'Học ngay',
    temple: 'Ngôi chùa\nKhmer',
    culture: 'Văn hóa\nKhmer',
    food: 'Ẩm thực\nKhmer',
    language_study: 'Học tiếng\nKhmer',
    ai_camera: 'AI Camera Khmer',
    som_rong_temple: 'Chùa Som Rong',
    oc_om_boc_festival: 'Lễ hội Oóc Om Bóc',
    tra_vinh_vn: 'Trà Vinh, VN',
    soc_trang_vn: 'Sóc Trăng, VN',
    promo_pagoda_title: 'Khám phá vẻ đẹp của các ngôi chùa Khmer',
    tagline: 'Khám phá nền văn hóa Khmer',
    search_placeholder: 'Tìm kiếm địa điểm...',
    location: 'Vị trí',
    search: 'Tìm kiếm',
    discovery_time: 'Thời gian khám phá',
    current_discovery: 'Khám phá gần đây',
    new_discovery: 'Khám phá mới',
    you: 'Bạn',

    // Auth Screens
    login_title: 'Đăng nhập',
    register_title: 'Đăng ký',
    register_account: 'Đăng ký tài khoản',
    email_label: 'Email',
    password_label: 'Mật khẩu',
    confirm_password_label: 'Xác nhận mật khẩu',
    fullname_placeholder: 'Họ và tên',
    processing: 'Đang xử lý...',
    registering: 'Đang tạo tài khoản...',
    login_with: 'Đăng nhập bằng',
    error_required: 'Điền đầy đủ thông tin',
    email_in_use: 'Email đã tồn tại hoặc đã được sử dụng bởi tài khoản khác',
    fullname_label: 'Họ và tên',
    select_interests_title: 'Bạn quan tâm đến gì nào',

    // New Home & Pagoda Strings
    welcome_hello: 'Chào mừng 👋',
    explore_categories: 'Danh mục khám phá',
    suggestions_for_you: 'Gợi ý cho bạn',
    oc_om_boc_time: 'Lễ hội truyền thống của người Khmer Nam Bộ',
    bun_nuoc_leo_desc: 'Gia vị đặc trưng tạo nên hương vị Khmer',
    reviews_label: 'đánh giá',
    no_results: 'Không tìm thấy kết quả',
    nguyet_hoa_vinh_long: 'phường Nguyệt Hóa, tỉnh Trà Vinh',
    loading_preparing: 'Đang chuẩn bị cho hành trình khám phá',
    loading_text: 'Đang tải...',
    register_success: 'Đăng ký tài khoản thành công',
    error_loading_temples: 'Không thể tải dữ liệu chùa Khmer',
    no_temple_data: 'Chưa có dữ liệu chùa Khmer',
    pagoda_detail_title: 'Chi tiết chùa',
    address_not_updated: 'Chưa cập nhật địa chỉ',
    navigate_btn: 'Chỉ đường',
    loading_content: 'Đang tải nội dung...',
    content_updating: 'Đang cập nhật nội dung',
    check_back_later: 'Vui lòng quay lại sau',
    rental_available: 'Cho thuê trang phục',
    description: 'Mô tả',
    no_description: 'Chưa có mô tả cho ngôi chùa này',
    view_map: 'Xem bản đồ',
    map_location: 'VỊ TRÍ TRÊN BẢN ĐỒ',
    view_directions: 'Xem đường đi',
    daily_knowledge: 'Kiến thức mỗi ngày',
    vocab_translation: 'Dịch văn bản',
    let_learn_khmer: 'Học tiếng Khmer cơ bản',
    let_learn_khmer_desc: 'Tìm hiểu và học một số từ vựng cơ bản',
    learn_by_topic: 'Học theo chủ đề',
    vocab_words: 'từ vựng',
    enter_text: 'Nhập văn bản',
    no_vocab_data: 'Không tìm thấy dữ liệu từ vựng chủ đề này',
    cat_greetings: 'Chào hỏi thông dụng',
    cat_numbers: 'Số đếm cơ bản',
    cat_family: 'Gia đình thân yêu',
    cat_food: 'Ẩm thực đặc sắc',
    'Gia đình thân yêu': 'Gia đình thân yêu',
    'Ẩm thực đặc sắc': 'Ẩm thực đặc sắc',
    'Chào hỏi thông dụng': 'Chào hỏi thông dụng',
    'Số đếm cơ bản': 'Số đếm cơ bản',
    'Đã thích bài viết của bạn': 'Đã thích bài viết của bạn',
    'Đã trả lời bình luận của bạn': 'Đã trả lời bình luận của bạn',
    'Đã bình luận về bài viết của bạn': 'Đã bình luận về bài viết của bạn',
    'Đã phản hồi ý kiến của bạn.': 'Đã phản hồi ý kiến của bạn',
    'បានចូលចិត្តអត្ថបទរបស់អ្នក': 'Đã thích bài viết của bạn',
    'បានឆ្លើយតបមតិរបស់អ្នក': 'Đã trả lời bình luận của bạn',
    'បានផ្តល់មតិលើអត្ថបទរបស់អ្នក': 'Đã bình luận về bài viết của bạn',
    'បានឆ្លើយតបទៅនឹងមតិកែលម្អរបស់អ្នក។': 'Đã phản hồi ý kiến của bạn',
    // Toast Messages
    login_success: 'Đăng nhập thành công',
    logout_success: 'Tài khoản đã được đăng xuất',
    notif_on: 'Đã bật nhắc nhở học tập',
    notif_off: 'Đã tắt nhắc nhở học tập',
    chat_on: 'Đã hiện trợ lý KhmerGo AI',
    chat_off: 'Đã ẩn trợ lý KhmerGo AI',
    lang_changed_vi: 'Đã chuyển sang tiếng Việt',
    lang_changed_km: 'Đã chuyển sang tiếng Khmer',

    // New localization keys
    notifications_title: 'Thông báo',
    no_notifications: 'Chưa có thông báo nào',
    just_now: 'Vừa xong',
    ai_intro: 'Tôi là KhmerGo AI - luôn sẵn sàng khám phá văn hóa, địa điểm và ngôn ngữ Khmer cùng bạn',
    thinking: 'Đang suy nghĩ...',
    clear_chat_history: 'Đã dọn dẹp lịch sử trò chuyện',
    clear_chat_history_success: 'Dọn dẹp lịch sử trò chuyện',
    refresh_analysis: 'Làm mới phân tích ngay',
    ai_error_connection: 'Xin lỗi, tôi gặp sự cố kết nối. Bạn thử lại nhé!',
    ai_chat_too_fast: 'Vui lòng đợi {seconds}s nữa nhé',
    view_details: 'Xem chi tiết',
    explore_now: 'Khám phá ngay',
    ask_anything_placeholder: 'Hỏi bất cứ điều gì...',
    welcome_back: 'Chào mừng bạn quay lại',
    forgot_password: 'Quên mật khẩu',
    use_other_account: 'Sử dụng tài khoản khác',
    account_blocked: 'Tài khoản của bạn đã bị khóa',
    ai_camera_ready: 'Sẵn sàng phân tích',
    ai_camera_idle_title: 'Chào bạn nhé',
    ai_camera_idle_desc: 'Tải ảnh lên hoặc chụp ảnh liên quan đến văn hóa Khmer Nam Bộ. KhmerGo AI sẽ hỗ trợ phân tích và giải thích chi tiết.',
    ai_camera_selected_desc: 'Đã chọn ảnh. Nhấn “Bắt đầu phân tích” để KhmerGo AI khám phá và giải thích ý nghĩa văn hóa của hiện vật này.',
    ai_analyzing: 'Đang phân tích hình ảnh...',
    ai_start_analysis: 'BẮT ĐẦU PHÂN TÍCH',
    ai_result_title: 'Phân tích từ AI',
    ai_unknown_object: 'Vật thể không xác định',
    ai_unknown_desc: 'Hiện vật này hiện chưa khớp với dữ liệu nhận diện trong hệ thống KhmerGo AI. Vui lòng thử lại với hình ảnh rõ nét hơn hoặc góc chụp khác để AI có thể phân tích chính xác hơn.',
    connection_error_title: 'Lỗi kết nối',
    connection_error_desc: 'Vui lòng thử lại sau giây lát.',
    clear_analysis_success: 'Đã dọn dẹp kết quả phân tích',
    features_label: 'Đặc điểm nhận diện',
    translation_error: 'Đã có lỗi xảy ra. Hãy kiểm tra kết nối mạng',
    avatar_label: 'Ảnh đại diện',
    terms_modal_title: 'ĐIỀU KHOẢN DỊCH VỤ',
    terms_modal_understand: 'ĐÃ HIỂU',
    reset_password: 'Đặt lại mật khẩu',
    enter_email_desc: 'Nhập email của bạn để đặt lại mật khẩu',
    send_code: 'Gửi yêu cầu',
    enter_otp_desc: 'Hướng dẫn đã gửi đến email của bạn\nVui lòng kiểm tra hộp thư đến',
    verify_code: 'Xác thực',
    new_password_desc: 'Tạo mật khẩu mới cho tài khoản của bạn',
    reset_password_success: 'Đã đặt lại mật khẩu thành công',
    cooldown_active: 'Vui lòng quay lại sau {time} để yêu cầu mã mới',

    // Tab Labels
    tab_home: 'Trang chủ',
    tab_community: 'Cộng đồng',
    tab_quiz: 'Thử thách',
    tab_profile: 'Hồ sơ',

    // Community
    comments_title: 'Bình luận',
    create_post_title: 'Tạo bài viết',
    edit_post_title: 'Sửa bài viết',
    post_placeholder: 'Chia sẻ khoảnh khắc đẹp...',
    submit_post: 'Đăng bài',
    update_post: 'Cập nhật',
    empty_posts: 'Chưa có bài viết nào',
    image_label: 'Ảnh',
    update_post_success: 'Cập nhật thành công',
    post_success: 'Đăng bài viết thành công',
    post_pending_approval: 'Đã gửi bài viết, chờ phê duyệt',
    action_failed: 'Thao tác thất bại',
    someone_liked: 'Đã thích bài viết của bạn',
    someone_replied: 'Đã trả lời bình luận của bạn',
    someone_commented: 'Đã bình luận bài viết của bạn',
    comment_success: 'Bình luận thành công',
    delete_comment_success: 'Đã xóa bình luận',
    delete_post_success: 'Đã xóa bài viết thành công',
    photo_permission_error: 'Vui lòng cấp quyền truy cập ảnh trong cài đặt',
    image_too_heavy: 'Ảnh quá nặng, hãy chọn ảnh khác',
    image_process_error: 'Lỗi xử lý hình ảnh',
    user_default: 'Người dùng',
    reply_action: 'Trả lời',
    delete_action: 'Xóa',
    first_comment_msg: 'Hãy là người đầu tiên bình luận',
    replying_to: 'Đang trả lời',
    write_comment_placeholder: 'Viết bình luận...',
    edit_post_menu: 'Chỉnh sửa bài viết',
    delete_post_menu: 'Xóa bỏ bài viết',
    delete_post_confirm: 'Xóa bài viết',
    cannot_undo: 'Hành động này không thể hoàn tác',

    // Intro Modal
    intro_title: 'Giới thiệu ứng dụng',
    intro_version_label: 'Phiên bản',
    intro_app_desc: 'Ứng dụng hỗ trợ nâng cao kiến thức về văn hóa người Khmer Nam Bộ.',
    intro_learn_title: 'KhmerGo giúp người dùng tìm hiểu về:',
    intro_learn_pagoda: '• Ngôi chùa Khmer',
    intro_learn_culture: '• Văn hóa Khmer',
    intro_learn_food: '• Ẩm thực Khmer',
    intro_learn_language: '• Học tiếng Khmer',
    intro_goal_title: 'Mục tiêu chung của ứng dụng:',
    intro_goal_1: '- Góp phần bảo tồn giá trị văn hóa Khmer Nam Bộ.',
    intro_goal_2: '- Hỗ trợ học tập và nghiên cứu.',
    intro_goal_3: '- Quảng bá văn hóa truyền thống đến cộng đồng.',
    intro_tech_label: 'Công nghệ sử dụng: ',
    intro_dev_label: 'Người phát triển: ',

    // Admin
    system: 'Hệ thống',
    feedback_replied_notif: 'Đã phản hồi góp\u00A0ý của bạn...',
    user_management: 'Quản lý người dùng',
    no_users: 'Chưa có người dùng nào',
    feedback_from: 'Phản hồi từ',
    loading_feedback: 'Đang tải phản hồi...',
    no_subject: 'Không có tiêu đề',
    edit_reply: 'Sửa phản hồi',
    reply_feedback: 'Phản hồi',
    user_no_feedback: 'Người dùng này chưa có phản hồi nào',
    lock_user_account: 'Khóa tài khoản',
    unlock_user_account: 'Mở khóa tài khoản',
    confirm_lock_user: 'Bạn có chắc chắn muốn tạm đình chỉ cho người dùng',
    confirm_unlock_user: 'Bạn có chắc chắn muốn mở lại quyền truy cập cho người dùng',
    lock_now: 'Khóa ngay',
    reply_placeholder: 'Nhập nội dung phản hồi...',
    send_reply_success: 'Đã gửi phản hồi tới người dùng',
    action_error: 'Không thể thực hiện thao tác này',
    send_reply: 'Phản hồi',
    lock: 'Khóa',
    unlock: 'Mở khóa',
    lock_success: 'Đã khóa tài khoản người dùng',
    unlock_success: 'Đã mở khóa tài khoản người dùng',
    mark_all_read: 'Đọc tất cả',
  },
  km: {
    // Common
    leaderboard: 'តារាងពិន្ទុ',
    medal: 'សមិទ្ធផលនៃចំណាត់ថ្នាក់',
    weekly: 'ប្រចាំសប្តាហ៍',
    all_time: 'គ្រប់ពេល',
    settings: 'ការកំណត់កម្មវិធី',
    language: 'ភាសា',
    vietnamese: 'ភាសាវៀតណាម',
    khmer: 'ភាសាខ្មែរ',
    back: 'ត្រឡប់ក្រោយ',
    confirm: 'បញ្ជាក់',
    close: 'បិទ',
    save: 'រក្សាទុក',
    cancel: 'បោះបង់',
    next: 'បន្ទាប់',
    continue: 'បន្តទៀត',
    exit: 'ចាកចេញ',
    login: 'ចូលគណនី',
    login_user: 'ចូលគណនី',
    // Settings Screen
    notif_settings: 'ការជូនដំណឹង',
    study_reminder: 'រំលឹកការសិក្សារាល់ថ្ងៃ',
    reminder_time: 'ម៉ោងរំលឹក',
    app_info: 'ព័ត៌មានកម្មវិធី',
    intro: 'អំពីយើង',
    version: 'ជំនាន់',
    assistant_settings: 'ជំនួយការ AI',
    show_chat_button: 'បង្ហាញប៊ូតុងជជែក AI',
    // Support Screen
    support_feedback: 'មតិកែលម្អរបស់អ្នកប្រើប្រាស់',
    feedback_type: 'ប្រភេទមតិកែលម្អ',
    suggestion: 'មតិកែលម្អ',
    report_issue: 'រាយការណ៍បញ្ហា',
    subject: 'ប្រធានបទ',
    detail: 'ខ្លឹមសារលម្អិត',
    send_feedback: 'ផ្ញើមតិកែលម្អ',
    login_to_send: 'ចូលដើម្បីផ្ញើមតិ',
    // Profile Screen
    my_profile: 'ប្រវត្តិរូបរបស់ខ្ញុំ',
    edit_profile: 'កែសម្រួលប្រវត្តិរូប',
    favorites: 'មាតិកាដែលចូលចិត្ត',
    achievements: 'សមិទ្ធផលរបស់ខ្ញុំ',
    logout: 'ចាកចេញ',
    logout_full: 'ចាកចេញពីគណនី',
    points: 'ពិន្ទុ',
    rank: 'ចំណាត់ថ្នាក់',
    guest: 'អ្នកទស្សនា',
    login_to_view: 'ចូលដើម្បីមើលព័ត៌មាន',
    login_to_use: 'ចូលដើម្បីប្រើប្រាស់មុខងារនេះ',
    logout_confirm_msg: 'តើអ្នកប្រាកដថាចង់ចាកចេញមែនទេ',
    login_required: 'តម្រូវឱ្យចូល',
    login_to_fav_msg: 'សូមចូលដើម្បីរក្សាទុក និងមើលបញ្ជីដែលអ្នកចូលចិត្ត',
    login_now: 'ចូលឥឡូវនេះ',
    no_favorites_yet: 'មិនទាន់មានមាតិកាដែលចូលចិត្តនៅឡើយទេ',
    explore_and_save_favs: 'សូមស្វែងយល់ និងរក្សាទុកអ្វីដែលអ្នកចូលចិត្ត',

    // Quiz Screen
    quiz_title: 'ការសាកល្បង',
    question: 'សំណួរ',
    start_quiz: 'ចាប់ផ្តើម',
    daily_challenge: 'ការសាកល្បងប្រចាំថ្ងៃ',
    correct: 'ត្រឹមត្រូវ',
    wrong_answer: 'ខុសហើយ',
    quiz_desc: 'ឆ្លងកាត់សំណួរដើម្បីទទួលបានពិន្ទុបន្ថែម',
    total_score: 'ពិន្ទុរួម',
    current_rank: 'ចំណាត់ថ្នាក់បច្ចុប្បន្ន',
    categories: 'ប្រធានបទ',
    history: 'ប្រវត្តិសាស្ត្រ',
    geography: 'ភូមិសាស្ត្រ',
    questions: 'សំណួរ',
    performance: 'សមិទ្ធផល',
    view_all: 'មើលទាំងអស់',
    completed: 'បានបញ្ចប់',
    badge: 'មេដាយ',
    badge_bronze: 'សំរឹទ្ធ',
    badge_silver: 'ប្រាក់',
    badge_gold: 'មាស',
    badge_platinum: 'ផ្លាទីន',
    badge_diamond: 'ពេជ្រ',
    badge_legend: 'រឿងព្រេង',
    rank_progress: 'វឌ្ឍនភាពឋានៈ',
    badge_locked: 'មិនទាន់សម្រេចបាន',
    badge_unlocked: 'សម្រេចបាន',
    quizzes_completed: 'ការសាកល្បងដែលបានបញ្ចប់',
    badge_locked_message: 'អ្នកត្រូវសម្រេចបាន {points} ពិន្ទុ ដើម្បីទទួលបានរូបសញ្ញា {name}។',
    congrats_earned: 'អបអរសាទរ! អ្នកទទួលបានរូបសញ្ញា',
    accuracy: 'ភាពត្រឹមត្រូវ',
    recent_performance: 'ផ្អែកលើការសាកល្បងថ្មីៗ',
    choose_topic: 'តើអ្នកចង់រៀនអ្វីនៅថ្ងៃនេះ',
    general_knowledge: 'ចំណេះដឹងទូទៅ',
    pagoda_quiz: 'វត្តអារាមខ្មែរ',
    culture_quiz: 'វប្បធម៌ខ្មែរ',
    food_quiz: 'ម្ហូបខ្មែរ',
    vocab_quiz: 'រៀនភាសាខ្មែរ',
    vocab_quiz_subtitle: 'ផ្គូផ្គងពាក្យខ្មែរ - វៀតណាម',
    vocab_challenge_questions: 'សំណួរសាកល្បងវាក្យសព្ទ',
    correct_answer_points_msg: '+5 ពិន្ទុសម្រាប់ចម្លើយត្រឹមត្រូវ',
    login_required_long_msg: 'អ្នកត្រូវចូលដើម្បីចូលរួមការសាកល្បង និងសន្សំពិន្ទុចំណាត់ថ្នាក់',
    exit_game_title: 'ចាកចេញពីហ្គេម',
    exit_game_msg: 'វឌ្ឍនភាពរបស់អ្នកនឹង\nមិនត្រូវបានរក្សាទុកទេ',
    replay: 'លេងម្តងទៀត',
    choose_another_quiz: 'ជ្រើសរើសការសាកល្បងផ្សេងទៀត',
    answered_correctly: 'ឆ្លើយបានត្រឹមត្រូវ',
    questions_count: 'សំណួរ',
    points_earned: 'ពិន្ទុដែលប្រមូលបាន',
    saving_results: 'កំពុងរក្សាទុកសមិទ្ធផល...',
    results_saved: 'រក្សាទុកសមិទ្ធផលបានជោគជ័យ',
    excellent: '🎉 ពូកែណាស់',
    well_done: '👏 ល្អណាស់',
    keep_it_up: '💪 ខិតខំឡើង',
    amazing: '🎉 អស្ចារ្យណាស់',
    incorrect: 'មិនទាន់ត្រឹមត្រូវ',
    correct_answer_label: 'ចម្លើយត្រឹមត្រូវ',
    continue_btn: 'បន្តទៀត',
    saving_points: 'កំពុងរក្សាទុកពិន្ទុ...',
    loading_questions: 'កំពុងទាញយកសំណួរ...',
    not_logged_in_title: 'អ្នកមិនទាន់បានចូលទេ',
    login_to_save_points: 'សូមចូលដើម្បីរក្សាទុកសមិទ្ធផល\nនិងសន្សំពិន្ទុរង្វាន់!',
    guest_login_msg: 'អ្នកត្រូវតែចូលដើម្បីចូលរួមការសាកល្បង\nរក្សាទុកសមិទ្ធផល និងសន្សំពិន្ទុរង្វាន់',
    maybe_later: 'ទុកពេលក្រោយ',
    go_back_now: 'ទុកពេលក្រោយ, ត្រឡប់ក្រោយ',
    preview_mode: 'របៀបពិនិត្យមើលជាមុន',
    question_label: 'សំណួរ',
    stay_and_play: 'បន្តទៀត',
    points_badge_unlocked: '+ {points} ពិន្ទុ',
    badge_reached_level: 'អ្នកបានឡើងដល់កម្រិត {rank}',
    badge_unlocked_name: 'អ្នកបានដោះសោគ្រឿងឥស្សរិយយស {rank}',
    badge_bronze_msg: 'អ្នកបានដោះសោគ្រឿងឥស្សរិយយសសំរឹទ្ធហើយ',
    badge_silver_msg: 'គ្រឿងឥស្សរិយយសប្រាក់ត្រូវបានដោះសោ',
    badge_gold_msg: 'អបអរសាទរ! អ្នកបានបើកសោគ្រឿងឥស្សរិយយសមាស។',
    badge_platinum_msg: 'អ្នកកំពុងខិតទៅជិតគ្រឿងឥស្សរិយយសប្លាទីនហើយ',
    badge_diamond_msg: 'គ្រឿងឥស្សរិយយសពេជ្រជារបស់អ្នកហើយ',
    badge_legend_msg: 'វីរបុរស KhmerGo បានបង្ហាញខ្លួនហើយ',
    rank_bronze: 'សំរឹទ្ធ',
    rank_silver: 'ប្រាក់',
    rank_gold: 'មាស',
    rank_platinum: 'ប្លាទីន',
    rank_diamond: 'ពេជ្រ',
    rank_legend: 'វីរបុរស',

    // Matching Game
    matching_challenge: 'ផ្គូផ្គងពាក្យ',
    matching_challenge_title: 'ការសាកល្បងផ្គូផ្គង',
    matching_challenge_desc: 'សូមផ្គូផ្គងពាក្យខ្មែរ និងអត្ថន័យភាសាវៀតណាមឱ្យបានលឿន',
    start_matching: 'ចាប់ផ្តើមផ្គូផ្គង',


    // Personal Info
    personal_info: 'ព័ត៌មានផ្ទាល់ខ្លួន',
    full_name: 'ឈ្មោះពេញ',
    email: 'អ៊ីមែល',
    change_password: 'ផ្លាស់ប្តូរពាក្យសម្ងាត់',
    current_password: 'ពាក្យសម្ងាត់បច្ចុប្បន្ន',
    new_password: 'ពាក្យសម្ងាត់ថ្មី',
    confirm_new_password: 'បញ្ជាក់ពាក្យសម្ងាត់ថ្មី',
    save_changes: 'រក្សាទុកការផ្លាស់ប្តូរ',
    error: 'កំហុស',
    name_required: 'ឈ្មោះមិនអាចនៅទំនេរទេ',
    unsaved_changes: 'ការផ្លាស់ប្តូរដែលមិនបានរក្សាទុក',
    exit_confirm_msg: 'តើអ្នកប្រាកដថាចង់ចាកចេញមែនទេ? ការផ្លាស់ប្តូរបស់អ្នកនឹងត្រូវបាត់បង់។',
    stay: 'នៅបន្ត',
    not_logged_in: 'មិនទាន់បានចូល',
    pass_fields_required: 'សូមបំពេញគ្រប់ព័ត៌មានដើម្បីប្តូរពាក្យសម្ងាត់',
    pass_mismatch: 'ពាក្យសម្ងាត់ថ្មីមិនត្រូវគ្នា',
    pass_too_short: 'ពាក្យសម្ងាត់ថ្មីយ៉ាងហោចណាស់ ៦ តួអក្សរ',
    user_not_found: 'រកមិនឃើញគណនី',
    wrong_old_pass: 'ពាក្យសម្ងាត់បច្ចុប្បន្នមិនត្រឹមត្រូវ',
    no_feedback_history: 'មិនទាន់មានប្រវត្តិមតិកែលម្អ',
    update_success: 'បច្ចុប្បន្នភាពបានជោគជ័យ',
    update_failed: 'បច្ចុប្បន្នភាពបរាជ័យ',
    // Support Screen Extra
    feedback_section: 'ផ្ញើមតិកែលម្អមកយើង',
    feedback_placeholder: 'បញ្ចូលខ្លឹមសារមតិកែលម្អ...',
    subject_placeholder: 'បញ្ចូលប្រធានបទមតិ...',
    subject_required: 'សូមបញ្ចូលប្រធានបទ',
    content_required: 'សូមបញ្ចូលខ្លឹមសារមតិ',
    feedback_success: 'បានផ្ញើមតិដោយជោគជ័យ! អរគុណ។',
    feedback_failed: 'ផ្ញើមតិបរាជ័យ។ សូមព្យាយាមម្តងទៀត។',
    delete_feedback_success: 'បានលុបខ្លឹមសារមតិកែលម្អ',
    delete_feedback_failed: 'មិនអាចលុបមតិកែលម្អបានទេ',
    feedback_history: 'ប្រវត្តិមតិកែលម្អ',
    feedback_content_label: 'ខ្លឹមសារ',
    no_content: 'គ្មានខ្លឹមសារ',
    system_reply: 'ប្រព័ន្ធឆ្លើយតប',
    no_feedback_yet: 'អ្នកមិនទាន់មានមតិកែលម្អនៅឡើយទេ',
    tap_to_see_guide: 'ចុចដើម្បីមើលការណែនាំលម្អិត',
    replied_status: 'បានឆ្លើយតប',
    pending_status: 'កំពុងរង់ចាំ',
    admin_reply: 'ការឆ្លើយតបរបស់ Admin',
    // FAQ Extra
    faq_how_to_use: 'របៀបប្រើកម្មវិធី',
    faq_how_to_quiz: 'របៀបធ្វើតេស្ត',
    faq_how_to_learn: 'របៀបចុះឈ្មោះ និងចូលប្រើប្រាស់',
    faq_use_content: 'សូម chào មកកាន់ KhmerGo! ដើម្បីប្រើកម្មវិធី អ្នក có thể ចាប់ផ្តើមដោយការរុករកវត្តអារាមនានានៅក្នុងទំព័រដើម ចូលរួមឆ្លើយសំណួរក្នុងផ្នែកសាកល្បង ដើម្បីបង្កើនពិន្ទុ និងតម្លើងឋានៈ។',
    faq_quiz_content: 'រាល់ការសាកល្បងនីមួយៗនឹងមានសំណួរអំពីវប្បធម៌ និងភាសាខ្មែរbox។ អ្នកត្រូវជ្រើសរើសចម្លើយដែលត្រឹមត្រូវក្នុងរយៈពេលកំណត់ ដើម្បីទទួលបានពិន្ទុបន្ថែម។',
    faq_learn_content: 'អ្នកអាចចុះឈ្មោះគណនីថ្មីដោយប្រើអ៊ីមែលនៅក្នុងទំព័រចុះឈ្មោះ។ បន្ទាប់ពីមានគណនីហើយ សូមប្រើព័ត៌មាននោះដើម្បីចូលប្រើប្រាស់ និងទទួលបានបទពិសោធន៍ពេញលេញពីកម្មវិធី ដូចជាការធ្វើតេស្ត និងការសន្សំពិន្ទុ។',

    // FAQ Detail Steps — Use
    faq_use_step1_title: '1. រុករកឥឡូវនេះ',
    faq_use_step1_desc: 'ចាប់ផ្តើមការធ្វើដំណើរនៅទំព័រដើម។ អ្នកអាចស្វែងរកវត្តអារាមបុរាណ ទីកន្លែងល្បីៗ និងពិធីបុណ្យពិសេសរបស់ជនជាតិខ្មែរណាមបូ។',
    faq_use_step2_title: '2. ស្វែងយល់បន្ថែម',
    faq_use_step2_desc: 'ទីកន្លែងនីមួយៗមានព័ត៌មានលម្អិតអំពីប្រវត្តិសាស្ត្រ ស្ថាបត្យកម្ម និងម្ហូបអាហារពិសេស។ សូមអានដោយយកចិត្តទុកដាក់ដើម្បីយល់ដឹងកាន់តែច្បាស់អំពីភាពស្រស់ស្អាតនៃប្រពៃណី។',
    faq_use_step3_title: '3. ឆ្លងកាត់ការសាកល្បង',
    faq_use_step3_desc: 'ចូលរួមឆ្លើយសំណួរកម្សាន្តនៅក្នុងផ្នែកការសាកល្បង។ ឆ្លើយត្រឹមត្រូវដើម្បីប្រមូលពិន្ទុ និងតម្លើងចំណាត់ថ្នាក់នៅក្នុងតារាងពិន្ទុសហគមន៍។',
    faq_use_step4_title: '4. ជជែកជាមួយ AI',
    faq_use_step4_desc: 'ប្រសិនបើអ្នកមានចម្ងល់ណាមួយ សូមចុចលើរូបសញ្ញា Chat ដើម្បីជជែកជាមួយជំនួយការ AI ឆ្លាតវៃរបស់ KhmerGo។',

    // FAQ Detail Steps — Quiz
    faq_quiz_step1_title: '1. ជ្រើសរើសប្រធានបទ',
    faq_quiz_step1_desc: 'អ្នកអាចជ្រើសរើសប្រធានបទដូចជា៖ វត្តអារាមខ្មែរ វប្បធម៌ ម្ហូបអាហារ ឬរៀនភាសាខ្មែរ ដើម្បីចាប់ផ្តើមការសាកល្បងចំណេះដឹង។',
    faq_quiz_step2_title: '2. លេងការសាកល្បង',
    faq_quiz_step2_desc: 'សំណួរនីមួយៗនឹងមាន ៤ ជម្រើស។ សូមគិតឱ្យបានច្បាស់ ហើយជ្រើសរើសចម្លើយត្រឹមត្រូវបំផុតក្នុងរយៈពេលកំណត់។',
    faq_quiz_step3_title: '3. ទទួលរង្វាន់',
    faq_quiz_step3_desc: 'បន្ទាប់ពីបញ្ចប់ អ្នកនឹងទទួលបានពិន្ទុបន្ថែមដោយផ្អែកលើចំនួនចម្លើយត្រឹមត្រូវ។ ពិន្ទុនេះប្រើដើម្បីតម្លើងចំណាត់ថ្នាក់សមាជិក។',
    faq_quiz_step4_title: '4. មើលចំណាត់ថ្នាក់',
    faq_quiz_step4_desc: 'មើលចំណាត់ថ្នាក់របស់អ្នកធៀបនឹងអ្នកប្រើប្រាស់ផ្សេងទៀតនៅក្នុងតារាងពិន្ទុរួម ដើម្បីខិតខំឲ្យបានទីតាំងកាន់តែខ្ពស់រៀងរាល់ថ្ងៃ។',

    // FAQ Detail Steps — Learn (Register/Login)
    faq_learn_step1_title: '1. ចូលទៅកាន់ប្រវត្តិរូប',
    faq_learn_step1_desc: 'ចុចលើរូបសញ្ញាប្រវត្តិរូបនៅរបារក្រោម បន្ទាប់មកជ្រើសរើសចូលគណនី ឬចុះឈ្មោះគណនី។',
    faq_learn_step2_title: '2. ចុះឈ្មោះឥឡូវនេះ',
    faq_learn_step2_desc: 'ប្រសិនបើអ្នកមិនទាន់មានគណនី សូមបញ្ចូលអ៊ីមែល និងពាក្យសម្ងាត់ដើម្បីបង្កើតថ្មី។ បន្ទាប់មកអ្នកអាចជ្រើសរើសប្រធានបទដែលអ្នកចាប់អារម្មណ៍។',
    faq_learn_step3_title: '3. សហគមន៍ខ្មែរ',
    faq_learn_step3_desc: 'នៅពេលចូលគណនីរួចហើយ អ្នកអាចចូលរួមផ្តល់មតិ ចែករំលែករូបភាព និងរក្សាទុកទីកន្លែងដែលអ្នកចូលចិត្ត។',
    faq_learn_step4_title: '4. ប្តូរពាក្យសម្ងាត់',
    faq_learn_step4_desc: 'អ្នកអាចប្តូរពាក្យសម្ងាត់ ធ្វើបច្ចុប្បន្នភាពព័ត៌មានផ្ទាល់ខ្លួន ឬគ្រប់គ្រងភាពឯកជននៅក្នុងផ្នែកការកំណត់គណនី។',

    // Home Screen
    promotions: 'ការផ្សព្វផ្សាយ',
    category: 'ប្រភេទ',
    see_all: 'មើលទាំងអស់...',
    get_coupon: 'ទទួលបានប័ណ្ណ',
    learn_now: 'រៀនឥឡូវនេះ',
    temple: 'វត្តអារាមខ្មែរ',
    culture: 'វប្បធម៌ខ្មែរ',
    food: 'ម្ហូបខ្មែរ',
    language_study: 'រៀនភាសាខ្មែរ',
    ai_camera: 'AI កាមេរ៉ា',
    som_rong_temple: 'វត្តសំពៅរុង',
    oc_om_boc_festival: 'ពិធីបុណ្យអកអំបុក',
    tra_vinh_vn: 'ត្រាវិញ, វៀតណាម',
    soc_trang_vn: 'សុកត្រាំង, វៀតណាម',
    promo_pagoda_title: 'ដំណើរស្វែងយល់ពីសម្រស់នៃវត្តអារាមខ្មែរ',
    tagline: 'ស្វែងយល់ពីវប្បធម៌ខ្មែរ',
    search_placeholder: 'ស្វែងរកទីតាំង...',
    location: 'ទីតាំង',
    search: 'ស្វែងរក',
    discovery_time: 'ពេលវេលាស្វែងយល់',
    current_discovery: 'ការស្វែងយល់ថ្មីៗ',
    new_discovery: 'ការស្វែងយល់ថ្មី',
    you: 'អ្នក',

    // Auth Screens
    login_title: 'ចូលគណនី',
    register_title: 'ចុះឈ្មោះ',
    register_account: 'ចុះឈ្មោះគណនី',
    email_label: 'អ៊ីមែល',
    password_label: 'ពាក្យសម្ងាត់',
    confirm_password_label: 'បញ្ជាក់ពាក្យសម្ងាត់',
    fullname_placeholder: 'ឈ្មោះពេញ',
    processing: 'កំពុងដំណើរការ...',
    registering: 'កំពុងបង្កើតគណនី...',
    login_with: 'ចូលតាមរយៈ',
    error_required: 'សូមបំពេញព័ត៌មានឱ្យគ្រប់គ្រាន់',
    email_in_use: 'អ៊ីមែលនេះមានរួចហើយ ឬត្រូវបានប្រើប្រាស់ដោយគណនីផ្សេងទៀត',
    fullname_label: 'ឈ្មោះពេញ',
    select_interests_title: 'តើអ្នកចាប់អារម្មណ៍អ្វីខ្លះ?',

    // New Home & Pagoda Strings
    welcome_hello: 'សូមស្វាគមន៍ 👋',
    explore_categories: 'ប្រភេទរុករក',
    suggestions_for_you: 'សំណូមពរសម្រាប់អ្នក',
    oc_om_boc_time: 'ប្រារព្ធឡើងក្នុងខែតុលារៀងរាល់ឆ្នាំ',
    bun_nuoc_leo_desc: 'ម្ហូបពិសេសល្បីឈ្មោះ រសជាតិខ្មែរណាមបូ',
    reviews_label: 'ការវាយតម្លៃ',
    no_results: 'រកមិនឃើញលទ្ធផល',
    nguyet_hoa_vinh_long: 'សង្កាត់ Nguyet Hoa ខេត្ត Tra Vinh',
    loading_preparing: 'កំពុងរៀបចំសម្រាប់ការធ្វើដំណើររុករក',
    loading_text: 'កំពុងទាញយក...',
    register_success: 'ការចុះឈ្មោះបានជោគជ័យ',
    error_loading_temples: 'មិនអាចទាញយកទិន្នន័យវត្តអារាមខ្មែរ',
    no_temple_data: 'មិនមានទិន្នន័យវត្តអារាមខ្មែរ',
    pagoda_detail_title: 'ព័ត៌មានលម្អិត vềវត្ត',
    address_not_updated: 'មិនទាន់មានអាសយដ្ឋាន',
    navigate_btn: 'នាំផ្លូវ',
    loading_content: 'កំពុងទាញយកមាតិកា...',
    content_updating: 'មាតិកាកំពុងត្រូវបានធ្វើបច្ចុប្បន្នភាព',
    check_back_later: 'សូមត្រលប់មកវិញនៅពេលក្រោយ',
    rental_available: 'ជួលសម្លៀកបំពាក់',
    description: 'ការពិពណ៌នា',
    no_description: 'មិនទាន់មានការពិពណ៌នាសម្រាប់វត្តនេះនៅឡើយទេ។',
    view_map: 'មើលផែនទី',
    map_location: 'ទីតាំងនៅលើផែនទី',
    view_directions: 'មើលផ្លូវធ្វើដំណើរ',
    daily_knowledge: 'ចំណេះដឹងប្រចាំថ្ងៃ',
    vocab_translation: 'បកប្រែវាក្យសព្ទ',
    let_learn_khmer: 'រៀនភាសាខ្មែររាប់បញ្ចូល',
    let_learn_khmer_desc: 'រៀននិងស្វែងយល់ពាក្យមូលដ្ឋានដើម្បីអាចនិយាយប្រាស្រ័យទាក់ទងដោយភាពជឿជាក់នៅពេលជួបបទពិសោធន៍ផ្ទាល់!',
    learn_by_topic: 'រៀនតាមប្រធានបទ',
    vocab_words: 'ពាក្យ',
    enter_text: 'វាយអត្ថបទរបស់អ្នកនៅទីនេះ',
    no_vocab_data: 'រកមិនឃើញទិន្នន័យវាក្យសព្ទសម្រាប់ប្រធានបទនេះទេ។',
    cat_greetings: 'ការសួរសុខទុក្ខបឋម',
    cat_numbers: 'លេខនិងការរាប់',
    cat_family: 'គ្រួសារនិងការហៅទូរសព្ទ',
    cat_food: 'អាហារនិងភេសជ្ជៈ',
    'Gia đình thân yêu': 'គ្រួសារនិងការហៅទូរសព្ទ',
    'Ẩm thực đặc sắc': 'អាហារនិងភេសជ្ជៈ',
    'Chào hỏi thông dụng': 'ការសួរសុខទុក្ខបឋម',
    'Số đếm cơ bản': 'លេខនិងការរាប់',
    'Đã thích bài viết của bạn': 'បានចូលចិត្តអត្ថបទរបស់អ្នក',
    'Đã trả lời bình luận của bạn': 'បានឆ្លើយតបមតិរបស់អ្នក',
    'Đã bình luận về bài viết của bạn': 'បានផ្តល់មតិលើអត្ថបទរបស់អ្នក',
    'Đã phản hồi ý kiến của bạn.': 'បានឆ្លើយតបទៅនឹងមតិកែលម្អរបស់អ្នក។',
    'បានចូលចិត្តអត្ថបទរបស់អ្នក': 'បានចូលចិត្តអត្ថបទរបស់អ្នក',
    'បានឆ្លើយតបមតិរបស់អ្នក': 'បានឆ្លើយតបមតិរបស់អ្នក',
    'បានផ្តល់មតិលើអត្ថបទរបស់អ្នក': 'បានផ្តល់មតិលើអត្ថបទរបស់អ្នក',
    'បានឆ្លើយតបទៅនឹងមតិកែលម្អរបស់អ្នក។': 'បានឆ្លើយតបទៅនឹងមតិកែលម្អរបស់អ្នក។',
    // Toast Messages
    login_success: 'បានចូលដោយជោគជ័យ',
    logout_success: 'បានចាកចេញពីគណនី',
    notif_on: 'បានបើកការរំលឹកការសិក្សា',
    notif_off: 'បានបិទការរំលឹកការសិក្សា',
    chat_on: 'បានបង្ហាញប៊ូតុងជំនួយការ AI',
    chat_off: 'បានលាក់ប៊ូតុងជំនួយការ AI',
    lang_changed_vi: 'បានប្តូរទៅជាភាសាវៀតណាម',
    lang_changed_km: 'បានប្តូរទៅជាភាសាខ្មែរ',

    // Khmer translations for new keys
    notifications_title: 'ការជូនដំណឹង',
    no_notifications: 'មិនទាន់មានការជូនដំណឹងនៅឡើយទេ',
    just_now: 'មុននេះបន្តិច',
    ai_intro: 'ខ្ញុំគឺជា KhmerGo AI - ត្រៀមខ្លួនជានិច្ចដើម្បីរុករកវប្បធម៌ ទីកន្លែង និងភាសាខ្មែរជាមួយអ្នក។',
    thinking: 'កំពុងគិត...',
    clear_chat_history: 'បានសម្អាតប្រវត្តិជជែក',
    clear_chat_history_success: 'សម្អាតប្រវត្តិជជែក',
    refresh_analysis: 'ធ្វើការវិភាគឡើងវិញឥឡូវនេះ',
    ai_error_connection: 'សូមអភ័យទោស ខ្ញុំមានបញ្ហាក្នុងការតភ្ជាប់។ សូមព្យាយាមម្តងទៀត',
    ai_chat_too_fast: 'សូមរង់ចាំ {seconds}វិនាទីទៀត',
    view_details: 'មើលលម្អិត',
    explore_now: 'រុករកឥឡូវនេះ',
    ask_anything_placeholder: 'សួរអ្វីក៏បាន...',
    welcome_back: 'សូមស្វាគមន៍ការត្រឡប់មកវិញ',
    forgot_password: 'ភ្លេចពាក្យសម្ងាត់',
    use_other_account: 'ប្រើគណនីផ្សេងទៀត',
    account_blocked: 'គណនីរបស់អ្នកត្រូវបានចាក់សោ',
    ai_camera_ready: 'ត្រៀមខ្លួនរួចរាល់សម្រាប់ការវិភាគ',
    ai_camera_idle_title: 'សួស្តីអ្នក',
    ai_camera_idle_desc: 'បង្ហោះរូបភាព ឬថតរូបពាក់ព័ន្ធនឹងវប្បធម៌ខ្មែរណាមបូ។ KhmerGo AI នឹងជួយវិភាគ និងពន្យល់លម្អិត។',
    ai_camera_selected_desc: 'រូបភាពត្រូវបានជ្រើសរើស។ ចុច "ចាប់ផ្តើមការវិភាគ" ដើម្បីឱ្យ KhmerGo AI រុករក និងពន្យល់ពីអត្ថន័យវប្បធម៌នៃវត្ថុនេះ។',
    ai_analyzing: 'កំពុងវិភាគរូបភាព...',
    ai_start_analysis: 'ចាប់ផ្តើមការវិភាគ',
    ai_result_title: 'ការវិភាគពី AI',
    ai_unknown_object: 'វត្ថុមិនស្គាល់អត្តសញ្ញាណ',
    ai_unknown_desc: 'វត្ថុនេះបច្ចុប្បន្នមិនទាន់ត្រូវគ្នានឹងទិន្នន័យសម្គាល់នៅក្នុងប្រព័ន្ធ KhmerGo AI នៅឡើយទេ។ សូមព្យាយាមម្តងទៀតជាមួយរូបភាពច្បាស់ជាងមុន ឬមុំថតផ្សេងទៀត ដើម្បីឱ្យ AI អាចវិភាគបានត្រឹមត្រូវជាងមុន។',
    connection_error_title: 'កំហុសក្នុងការតភ្ជាប់',
    connection_error_desc: 'សូមព្យាយាមម្តងទៀតក្នុងពេលបន្តិចទៀតនេះ។',
    clear_analysis_success: 'បានសម្អាតលទ្ធផលវិភាគ',
    features_label: 'លក្ខណៈសម្គាល់',
    translation_error: 'មានកំហុសបានកើតឡើង។ សូមពិនិត្យមើលការតភ្ជាប់បណ្តាញរបស់អ្នក។',
    avatar_label: 'រូបតំណាង',
    terms_modal_title: 'លក្ខខណ្ឌសេវាកម្ម',
    terms_modal_understand: 'បានយល់',
    reset_password: 'ដាក់ពាក្យសម្ងាត់ឡើងវិញ',
    enter_email_desc: 'បញ្ចូលអ៊ីមែលរបស់អ្នកដើម្បីទទួលបានការណែនាំអំពីការកំណត់ពាក្យសម្ងាត់ឡើងវិញ',
    send_code: 'ផ្ញើសំណើ',
    enter_otp_desc: 'ការណែនាំត្រូវបានផ្ញើទៅអ៊ីមែលរបស់អ្នករួចហើយ។\nសូមពិនិត្យមើលប្រអប់សំបុត្ររបស់អ្នក។',
    verify_code: 'បញ្ជាក់',
    new_password_desc: 'បង្កើតពាក្យសម្ងាត់ថ្មីសម្រាប់គណនីរបស់អ្នក',
    reset_password_success: 'បានដាក់ពាក្យសម្ងាត់ឡើងវិញដោយជោគជ័យ',
    cooldown_active: 'សូមព្យាយามម្តងទៀតបន្ទាប់ពី {time} ដើម្បីស្នើសុំលេខកូដថ្មី',

    // Tab Labels
    tab_home: 'ទំព័រដើម',
    tab_community: 'សហគមន៍',
    tab_quiz: 'ការសាកល្បង',
    tab_profile: 'ប្រវត្តិរូប',

    // Community
    comments_title: 'មតិយោបល់',
    create_post_title: 'បង្កើតអត្ថបទ',
    edit_post_title: 'កែសម្រួលអត្ថបទ',
    post_placeholder: 'ចែករំលែកគ្រាដ៏ស្រស់ស្អាត...',
    submit_post: 'ចុះផ្សាយ',
    update_post: 'ធ្វើបច្ចុប្បន្នភាព',
    empty_posts: 'មិនទាន់មានអត្ថបទនៅឡើយទេ',
    image_label: 'រូបភាព',
    update_post_success: 'បានធ្វើបច្ចុប្បន្នភាពអត្ថបទ',
    post_success: 'បានចុះផ្សាយអត្ថបទ',
    post_pending_approval: 'បានផ្ញើអត្ថបទ រង់ចាំការអនុម័ត!',
    action_failed: 'ប្រតិបត្តិការបរាជ័យ',
    someone_liked: 'បានចូលចិត្តអត្ថបទរបស់អ្នក',
    someone_replied: 'បានឆ្លើយតបមតិរបស់អ្នក',
    someone_commented: 'បានផ្តល់មតិលើអត្ថបទរបស់អ្នក',
    comment_success: 'បានផ្តល់មតិយោបល់ជោគជ័យ',
    delete_comment_success: 'បានលុបមតិ',
    delete_post_success: 'បានលុបអត្ថបទ',
    photo_permission_error: 'សូមផ្តល់សិទ្ធិចូលប្រើរូបភាពនៅក្នុងការកំណត់',
    image_too_heavy: 'រូបភាពធ្ងន់ពេក សូមជ្រើសរើសរូបភាពផ្សេង',
    image_process_error: 'កំហុសក្នុងការព្យាបាលរូបភាព',
    user_default: 'អ្នកប្រើប្រាស់',
    reply_action: 'ឆ្លើយតប',
    delete_action: 'លុប',
    first_comment_msg: 'សូមក្លាយជាអ្នកដំបូងគេដែលផ្តល់មតិ',
    replying_to: 'កំពុងឆ្លើយតប',
    write_comment_placeholder: 'សរសេរមតិយោបល់...',
    edit_post_menu: 'កែសម្រួលអត្ថបទ',
    delete_post_menu: 'លុបអត្ថបទ',
    delete_post_confirm: 'លុបអត្ថបទ',
    cannot_undo: 'សកម្មភាពនេះមិនអាចផ្លាស់ប្តូរបានទេ',

    // Intro Modal
    intro_title: 'ការណែនាំកម្មវិធី',
    intro_version_label: 'ជំនាន់',
    intro_app_desc: 'កម្មវិធីជួយលើកកម្ពស់ចំណេះដឹងអំពីវប្បធម៌ជនជាតិខ្មែរណាមបូ។',
    intro_learn_title: 'KhmerGo ជួយអ្នកប្រើប្រាស់ស្វែងយល់អំពី:',
    intro_learn_pagoda: '• វត្តអារាមខ្មែរ',
    intro_learn_culture: '• វប្បធម៌ខ្មែរ',
    intro_learn_food: '• ម្ហូបខ្មែរ',
    intro_learn_language: '• រៀនភាសាខ្មែរ',
    intro_goal_title: 'គោលបំណងទូទៅរបស់កម្មវិធី:',
    intro_goal_1: '- រួមចំណែកអភិរក្សតម្លៃវប្បធម៌ខ្មែរណាមបូ។',
    intro_goal_2: '- គាំទ្រការរៀនសូត្រ និងការស្រាវជ្រាវ។',
    intro_goal_3: '- ផ្សព្វផ្សាយវប្បធម៌ប្រពៃណីទៅកាន់សហគមន៍។',
    intro_tech_label: 'បច្ចេកវិទ្យាប្រើប្រាស់: ',
    intro_dev_label: 'អ្នកអភិវឌ្ឍន៍: ',

    // Admin
    system: 'ប្រព័ន្ធ',
    feedback_replied_notif: 'បានឆ្លើយតបទៅនឹងមតិកែលម្អរបស់អ្នក។',
    user_management: 'ការគ្រប់គ្រងអ្នកប្រើប្រាស់',
    no_users: 'មិនទាន់មានអ្នកប្រើប្រាស់នៅឡើយទេ',
    feedback_from: 'មតិកែលម្អពី',
    loading_feedback: 'កំពុងទាញយកមតិកែលម្អ...',
    no_subject: 'គ្មានប្រធានបទ',
    edit_reply: 'កែសម្រួលការឆ្លើយតប',
    reply_feedback: 'ឆ្លើយតបមតិកែលម្អ',
    user_no_feedback: 'អ្នកប្រើប្រាស់នេះមិនទាន់មានមតិកែលម្អនៅឡើយទេ',
    lock_user_account: 'ចាក់សោគណនី',
    unlock_user_account: 'ដោះសោគណនី',
    confirm_lock_user: 'តើអ្នកប្រាកដថាចង់ផ្អាកជាបណ្តោះអាសន្នសម្រាប់អ្នកប្រើប្រាស់',
    confirm_unlock_user: 'តើអ្នកប្រាកដថាចង់បើកសិទ្ធិចូលប្រើឡើងវិញសម្រាប់អ្នកប្រើប្រាស់',
    lock_now: 'ចាក់សោឥឡូវនេះ',
    reply_placeholder: 'បញ្ចូលខ្លឹមសារឆ្លើយតប...',
    send_reply_success: 'បានផ្ញើការឆ្លើយតបទៅអ្នកប្រើប្រាស់',
    action_error: 'មិនអាចអនុវត្តសកម្មភាពនេះបានទេ។',
    send_reply: 'ឆ្លើយតប',
    lock: 'ចាក់សោ',
    unlock: 'ដោះសោ',
    lock_success: 'ចាក់សោគណនីបានជោគជ័យ',
    unlock_success: 'បើកសិទ្ធិចូលប្រើឡើងវិញបានជោគជ័យ',
    mark_all_read: 'អានទាំងអស់',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLangState] = useState<Language>('vi');

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const savedLang = await AsyncStorage.getItem('appLanguage');
      if (savedLang === 'vi' || savedLang === 'km') {
        setLangState(savedLang);
      }
    } catch (error) {
      // Silent fail
    }
  };

  const setLanguage = async (lang: Language) => {
    setLangState(lang);
    try {
      await AsyncStorage.setItem('appLanguage', lang);
    } catch (error) {
      // Silent fail
    }
  };

  const t = (key: string) => {
    const translation = translations[language][key as keyof typeof translations['vi']];
    if (!translation) {
      return translations['vi'][key as keyof typeof translations['vi']] || key;
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
